# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)



platform :android do
  desc "producti app"
  lane :distribute do
      build_android_app( 
          flavor: "staging",
          build_type: "Release"
      )
      # build_android_app is a built-in fastlane action.
      release = firebase_app_distribution(
          APP_ID: "1:217146418423:android:51f4361b23ab1e31041ff2",
          groups: "internal-testers",
          release_notes: "fix bugs",
          apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      )
      debug(release)
  end
end

platform :android do
  desc "deploy to firebase"
  lane :deploy do
      firebase_app_distribution(
          app: "1:217146418423:android:51f4361b23ab1e31041ff2",
          groups: "internal-testers",
          release_notes: "fix bugs",
          apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
          debug: true
      )
  end
end

platform :android do
  desc "increment version code"
  lane :increment_version_code do
      increment_version_code(
          gradle_file_path: "app/build.gradle"
      )
  end
end

platform :android do
  desc "flutter clean"
  lane :clean do
      sh("flutter clean")
  end
end

platform :android do
  desc "automatically release notes"
  lane :release_notes do
      changelog_from_git_commits(
          between: ["develop", "master"]
      )
  end
end

platform :android do
  desc "flutter pub get"
  lane :pub_get do
      sh("flutter pub get")
  end
end